### ISSUE TITLE
No weather data

### ISSUE THREAD

**Issue by erkr** [Makin-Things/platinum-weather-card#27]
**Checklist:**

- [ ] I updated to the latest version available
- [ ] I cleared the cache of my browser

**Release with the issue:**
0.0.2
**Last working release (if known):**

**Browser and Operating System:**
Companion app ios (safari)

**Description of problem:**
I like the example which is really attractive. But the configuration  options  are not really self explaining. I found one mandatory entity. Although I  selected my standard HA weather entity, the card doesn't populate with weather data. 
In the card, only entities can be selected, no attributes?!
![image](https://user-images.githubusercontent.com/4363599/177411225-abe79309-0b26-4ab2-a7df-a289b73ce2f7.jpeg)
I also don't see any configuration option to choose a weather data provider.
When I try to configure the locale, there are no options 

**Javascript errors shown in the web inspector (if applicable):**

```

```

**Additional information:**
I'm located in the Netherlands, Europe, and thus is how the data of the default weather integrations looks like :
``` 
temperature: 17
humidity: 55
pressure: 1024.3
wind_bearing: 324.7
wind_speed: 16.6
forecast:
  - condition: cloudy
    precipitation: 0
    temperature: 22.4
    templow: 10.4
    datetime: '2022-07-06T10:00:00+00:00'
    wind_bearing: 317.3
    wind_speed: 15.8
  - condition: cloudy
    precipitation: 0.7
    temperature: 19.8
    templow: 15.4
    datetime: '2022-07-07T10:00:00+00:00'
    wind_bearing: 320.9
    wind_speed: 24.8
  - condition: cloudy
    precipitation: 0.1
    temperature: 20.1
    templow: 11.4
    datetime: '2022-07-08T10:00:00+00:00'
    wind_bearing: 341.4
    wind_speed: 12.2
  - condition: rainy
    precipitation: 1.2
    temperature: 23.2
    templow: 13.5
    datetime: '2022-07-09T10:00:00+00:00'
    wind_bearing: 290
    wind_speed: 19.8
  - condition: cloudy
    precipitation: 0.3
    temperature: 18.7
    templow: 13.9
    datetime: '2022-07-10T10:00:00+00:00'
    wind_bearing: 344.6
    wind_speed: 15.5
attribution: >-
  Weather forecast from met.no, delivered by the Norwegian Meteorological
  Institute.
friendly_name: Home57
```
