### ISSUE TITLE
Forecast tooltips hang over edge of card

### ISSUE THREAD

**Issue by scotty1395** [Makin-Things/platinum-weather-card#28]
**Checklist:**

- [x] I updated to the latest version available
- [x] I cleared the cache of my browser

**Release with the issue:**
0.0.2

**Last working release (if known):**

**Browser and Operating System:**
Windows 11/Firefox, iOS/HA app

**Description of problem:**

The forecast tooltips hang over the edge of the card. This causes the card to take up empty horizontal space even when they are not displayed or disabled.
This results in the next card on the dashboard to be displayed below rather than next to the platinum card when there is room to display them side by side.
This also causes the dashboard on the iOS app to be horizontally scrollable into empty space.

Reducing the number of days displayed to 2 stops the tooltip from hanging over the edge of the card and solves the problem, but isn't ideal only having two days displayed.

![image](https://user-images.githubusercontent.com/56659709/177453218-80053291-1219-4843-a823-fb2d12cd52ec.png)
![37A91E9E-93AC-4FB7-9533-0E80DD577356](https://user-images.githubusercontent.com/56659709/177453291-3cbb1155-c6b9-4e59-900b-39911574a870.jpeg)

**Javascript errors shown in the web inspector (if applicable):**

```

```

**Additional information:**

**Comment by Makin-Things** [comment]
Acknowledged but a low priority right now. I need to get to writing some half decent doco for the new card as a priority.
I personally had the tooltips and would prefer to just get rid of them. Have you tried the new vertical daily forecast layout?

**Comment by Makin-Things** [comment]
0.0.3 has been released that addresses this.

**Comment by grastraa** [comment]
I still run into this issue on 0.0.3

To solve it, I added the solution I used for the [bom-weather-card](https://github.com/DavidFW1960/bom-weather-card), `tooltip_width: 90` this seems to be the maximum value I could use for the card to display correctly on all my devices.

As I understand it, YAML options not added to the visual editor are planned to be removed. As such, I would greatly appreciate it's addition to the visual editor.

Another thing to note is that the line height when displaying 2 lines of tooltip seems like it could do with a reduction.
![image](https://user-images.githubusercontent.com/67679349/180053356-886604d7-fb9c-4cfc-8f18-2e9737f204a1.png)

I really hope the tooltips remain an option, as they quickly allow give an overview for upcoming days where the same icon is used for various related conditions such as "shower or two", "a few showers", "showers developing" etc.

**Comment by DavidFW1960** [comment]
We have not included any styling in the GUI editor yet but the card still uses some of the yaml options. Styling is going to be added to the card

**Comment by Makin-Things** [comment]
Reopening to remind me to take another look at this.
For the default width of tooltips (110px) to not fit I think you must not be showing cards at full size (HA tries to keep cards 492px wide if there is enough space).

**Comment by Makin-Things** [comment]
@grastraa can I get an update on this from you. I am keen to understand why you are having issues. What environment are you having a problem in and if you are able to use debug tools, what is the width of the card?

**Comment by grastraa** [comment]
**Home Assistant 2022.7.6 Supervisor 2022.07.0 Operating System 8.2 Frontend 20220707.1 - latest** 
Default Masonry view with code as follows:
```
type: vertical-stack
cards:
  - card_config_version: 4
    custom1_icon: phu:outside-temp
    custom1_units: °C
    custom1_value: sensor.balcony_temperature
    custom2_icon: si:rainmeter
    custom2_units: '%'
    custom2_value: sensor.balcony_humidity
    custom3_icon: tc:dew-point-perception-hand
    custom3_units: ‎
    custom3_value: sensor.balcony_perception
    custom4_icon: tc:thermal-perception-hand
    custom4_value: sensor.balcony_simmerzone
    daily_extended_forecast_days: 7
    daily_extended_name_attr: state
    daily_extended_use_attr: true
    daily_forecast_days: 5
    daily_forecast_layout: horizontal

    [entity list removed]

    extended_name_attr: state
    extended_use_attr: true
    option_daily_show_extended: true
    option_icon_set: hybrid
    option_pressure_decimals: 1
    option_static_icons: false
    option_time_format: 24hour
    option_today_decimals: false
    option_tooltips: true
    section_order:
      - title
      - overview
      - extended
      - slots
      - daily_forecast
    show_decimals: true
    show_section_title: true
    show_separator: true
    slot_l1: observed_min
    slot_l2: observed_max
    slot_l3: rainfall
    slot_l4: uv_summary
    slot_l5: wind
    slot_l6: custom1
    slot_l7: custom4
    slot_l8: remove
    slot_r1: forecast_min
    slot_r2: forecast_max
    slot_r3: popforecast
    slot_r4: fire_summary
    slot_r5: pressure
    slot_r6: custom2
    slot_r7: custom3
    slot_r8: remove
    type: custom:platinum-weather-card
```

**Latest HA app for Android on a [OnePlus7](https://www.gsmarena.com/oneplus_7-9623.php) 1080 x 2340 pixels:**
![image](https://user-images.githubusercontent.com/67679349/181043661-8600aaee-641b-41c3-b21d-d4fb802f0de0.png)
browser_mod sensor info for this device reports:
`width: 384`
`height: 804`
`Mozilla/5.0 (Linux; Android 11; GM1900 Build/RKQ1.201022.002; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/103.0.5060.71 Mobile Safari/537.36 Home Assistant/2022.6.0-2398 (Android 11; GM1900)`

There appears to be an issue with dead-space either side of the text displayed. Perhaps there are two overlapping issues here?

**Simulating a similar mobile view on firefox based on the user agent and resolution reported by this sensor (+ already known and assumed DPR):**
![image](https://user-images.githubusercontent.com/67679349/181052108-46a84b28-e086-4a48-b66b-624057cc60b7.png)
This results in a much milder overspill as the dead-space issue doesn't seem to be present for some reason.
Dev tools using this simulated view gives me the following:
![image](https://user-images.githubusercontent.com/67679349/181053151-34885506-bf62-4954-8b7e-c1a727b3cd0f.png)
![image](https://user-images.githubusercontent.com/67679349/181052642-28087b1d-57ff-49a9-9bd5-25638893de7b.png)
In this simulation, upping the screens width from `384` to `410` eliminates the issue. 
I know this sandbox doesn't seem quite the same as the HA app for whatever reason, but it's all I knew how to do.
I'm also unsure if the value needed to eliminate this issue will chance depending on the length of text displayed.

I have also had this issue on my partners Pixel 6 with the old weather card, thought I haven't had a chance to look since updating to this card.
When attempting to simulate her device which reports as `412x852` via browser_mod, the issue is not present, probably because the issue present milder in my firefox sandbox where the dead-space isn't present.

I have a slew of common HACS lovelace components installed that I use, which I realise may be effecting the situation. Unfortunate that I don't have a set up I can sandbox a clean HA instance into to control for that.
