### ISSUE TITLE
Wrong days in card

### ISSUE THREAD

**Issue by erkr** [Makin-Things/platinum-weather-card#31]
Last attempt: As reported before. There is really one day missing in the card and the data is one day off. The data for Wednesday is on presented Tuesday in your card:
![image](https://user-images.githubusercontent.com/4363599/178027572-640ce079-5222-4f88-bbe6-9db2ea6fc5a3.jpeg)

**Comment by bkr1969** [comment]
Can you please show the code you used to get this working? (Not that I can find the card to install now anyway)

**Comment by erkr** [comment]
Of course:
```
card_config_version: 4
daily_forecast_days: 5
daily_forecast_layout: horizontal
entity_current_conditions: weather.home
entity_current_text: weather.home
entity_forecast_high_temp_1: weather.home
entity_forecast_icon_1: weather.home
entity_forecast_low_temp_1: weather.home
entity_forecast_max: weather.home
entity_forecast_min: weather.home
entity_humidity: weather.home
entity_pop: weather.home
entity_pos_1: weather.home
entity_possible_today: weather.home
entity_possible_tomorrow: weather.home
entity_pressure: weather.home
entity_summary_1: weather.home
entity_sun: sun.sun
entity_temperature: weather.home
entity_visibility: weather.home
entity_wind_bearing: weather.home
entity_wind_speed: weather.home
extended_use_attr: false
option_daily_show_extended: true
option_icon_set: hybrid
option_static_icons: false
option_time_format: 24hour
option_today_decimals: true
option_tooltips: false
section_order:
  - title
  - overview
  - extended
  - slots
  - daily_forecast
show_decimals: true
show_section_title: true
slot_l1: forecast_max
slot_l2: forecast_min
slot_l3: remove
slot_l4: pressure
slot_l5: sun_next
slot_l6: remove
slot_l7: remove
slot_l8: remove
slot_r1: possible_today
slot_r2: humidity
slot_r3: wind
slot_r4: remove
slot_r5: sun_following
slot_r6: remove
slot_r7: remove
slot_r8: remove
text_card_title: Geldrop
type: custom:platinum-weather-card
```

**Comment by bkr1969** [comment]
OK. Thanks, that helps, but now I still cant find this card in HACS after uninstalling this morning.

**Comment by DavidFW1960** [comment]
Try updating hacs

**Comment by erkr** [comment]
The missing error is solved with the HACs update.
But this issue is about presenting the weather dat one day off. See diff with the standard card. That is not solved

**Comment by DavidFW1960** [comment]
Check what the weather entity is showing. Is it the same as the card?

**Comment by Makin-Things** [comment]
@erkr there is nothing I can do if you don't include both an image of the card and the state of your weather entity.
The intention of the card is to use the slots section for the details of today, which means including it again in the next 5 days forecast is duplicating the data and wasting precious real-estate.
But look at the data from met.no for Amsterdam it looks like there is a problem with the integration (hard for me to confirm though because HA fails to deal with converting timestamps  of sensors that are in a different timezone). But to me it currently looks like it is 2am on the 11th in Amsterdamn, but the first forecast data included by the integration is timestamped for the 12th. Where is today's forecast data?
I am also struggling to find any website with a forecast for Amsterdam that provides the same information as the met.no integration (even the website that met.no send you to for forecasts is vastly different).

**Comment by erkr** [comment]
@Makin-Things 
I guess the todays forecast is not present in the weather entity, only the actual conditions, and a five day outlook.
Please note that I'm in the same time zone as met.no. The Netherlands are located just more south. So the time stamps in the data are correct:
``` 
temperature: 15.9
temperature_unit: °C
humidity: 88
pressure: 1024.4
pressure_unit: hPa
wind_bearing: 351.8
wind_speed: 7.9
wind_speed_unit: km/h
visibility_unit: km
precipitation_unit: mm
forecast:
  - condition: partlycloudy
    datetime: '2022-07-12T10:00:00+00:00'
    wind_bearing: 217.1
    temperature: 29
    templow: 13.4
    wind_speed: 9
    precipitation: 0
  - condition: cloudy
    datetime: '2022-07-13T10:00:00+00:00'
    wind_bearing: 250.4
    temperature: 29.3
    templow: 20.3
    wind_speed: 18
    precipitation: 0
  - condition: partlycloudy
    datetime: '2022-07-14T10:00:00+00:00'
    wind_bearing: 5.5
    temperature: 24.5
    templow: 16.2
    wind_speed: 17.6
    precipitation: 0
  - condition: cloudy
    datetime: '2022-07-15T10:00:00+00:00'
    wind_bearing: 294.1
    temperature: 22.6
    templow: 14.1
    wind_speed: 13.3
    precipitation: 0
  - condition: sunny
    datetime: '2022-07-16T10:00:00+00:00'
    wind_bearing: 316.8
    temperature: 24.8
    templow: 14.5
    wind_speed: 16.6
    precipitation: 0
attribution: >-
  Weather forecast from met.no, delivered by the Norwegian Meteorological
  Institute.
``` 
The two cards:
![image](https://user-images.githubusercontent.com/4363599/178204788-2b11192b-9f17-4978-83db-b2efe8085e6d.jpeg)

Forecast data of the Apple weather app as a reference:
![image](https://user-images.githubusercontent.com/4363599/178204911-320bfc43-50c5-479d-8075-2861d577b7f7.jpeg)

For the todays min and max, I will raise an issue for the met.no integration, and propose to leave the min and max entity in the card empty for now

Best Eric

**Comment by erkr** [comment]
Hi
Yes there wildly vary. Met.no is mostly more accurate for my area.
I in the mean time configured open-meteo as second one. Here todays forecast included:
``` 

temperature: 17.3
temperature_unit: °C
pressure_unit: hPa
wind_bearing: 336
wind_speed: 7.9
wind_speed_unit: km/h
visibility_unit: km
precipitation_unit: mm
forecast:
  - datetime: '2022-07-11'
    condition: cloudy
    wind_bearing: 0
    temperature: 25.3
    templow: 14.3
    wind_speed: 14.3
    precipitation: 0
  - datetime: '2022-07-12'
    condition: cloudy
    wind_bearing: 324
    temperature: 30
    templow: 13.7
    wind_speed: 10
    precipitation: 0
  - datetime: '2022-07-13'
    condition: rainy
    wind_bearing: 286
    temperature: 27.1
    templow: 14.8
    wind_speed: 15.4
    precipitation: 0.2
  - datetime: '2022-07-14'
    condition: fog
    wind_bearing: 350
    temperature: 24.5
    templow: 11.2
    wind_speed: 12.9
    precipitation: 0
  - datetime: '2022-07-15'
    condition: cloudy
    wind_bearing: 351
    temperature: 22.9
    templow: 11.6
    wind_speed: 8.9
    precipitation: 0
  - datetime: '2022-07-16'
    condition: sunny
    wind_bearing: 69
    temperature: 27.7
    templow: 12.1
    wind_speed: 7.7
    precipitation: 0
  - datetime: '2022-07-17'
    condition: partlycloudy
    wind_bearing: 117
    temperature: 33.8
    templow: 15.5
    wind_speed: 12.9
    precipitation: 0
friendly_name: Home57
```

**Comment by erkr** [comment]
Update: just past midnight, the one day off issue also occurs with the open-meteo integration. So just after 24h, the forecast for i.e Tuesday was used for Wednesday etc. Next morning the dat information was mapped correct again. Guess after the next fetch of weather data.

The card should use the date information that is included in the forecasts and not start counting, presuming the first forecast entry is for today.

**Comment by VDRainer** [comment]
For me only the icons are off one day, the values are ok.
Here the icon from today (Friday) is shown for tomorrow.
![20220722_133932](https://user-images.githubusercontent.com/26381449/180432875-1b7fa9d8-6acc-4218-8f4f-6908ddb273bd.png)
The left two cards are the custom:weather-card and the core weather card.
All cards use the same weather.openweathermap
```
temperature: 23.1
temperature_unit: °C
humidity: 61
pressure: 1019
pressure_unit: hPa
wind_bearing: 358
wind_speed: 2.99
wind_speed_unit: km/h
visibility_unit: km
precipitation_unit: mm
forecast: 
- condition: sunny
  precipitation_probability: 6
  datetime: '2022-07-22T11:00:00+00:00'
  wind_bearing: 5
  temperature: 30.4
  templow: 13.8
  wind_speed: 10.37
  precipitation: 0
- condition: rainy
  precipitation_probability: 100
  datetime: '2022-07-23T11:00:00+00:00'
  wind_bearing: 294
  temperature: 28.2
  templow: 15.5
  wind_speed: 23.9
  precipitation: 3.04
- condition: cloudy
  precipitation_probability: 0
  datetime: '2022-07-24T11:00:00+00:00'
  wind_bearing: 28
  temperature: 31
  templow: 14.6
  wind_speed: 9.36
  precipitation: 0
- condition: rainy
  precipitation_probability: 28
  datetime: '2022-07-25T11:00:00+00:00'
  wind_bearing: 264
  temperature: 35
  templow: 17.2
  wind_speed: 21.1
  precipitation: 0.23
- condition: rainy
  precipitation_probability: 66
  datetime: '2022-07-26T11:00:00+00:00'
  wind_bearing: 277
  temperature: 27
  templow: 16.1
  wind_speed: 24.3
  precipitation: 0.83
- condition: cloudy
  precipitation_probability: 0
  datetime: '2022-07-27T11:00:00+00:00'
  wind_bearing: 316
  temperature: 27.4
  templow: 12
  wind_speed: 19.69
  precipitation: 0
- condition: partlycloudy
  precipitation_probability: 0
  datetime: '2022-07-28T11:00:00+00:00'
  wind_bearing: 317
  temperature: 30.9
  templow: 11.3
  wind_speed: 13.9
  precipitation: 0
- condition: cloudy
  precipitation_probability: 8
  datetime: '2022-07-29T11:00:00+00:00'
  wind_bearing: 287
  temperature: 26.2
  templow: 14.7
  wind_speed: 22.43
  precipitation: 0

attribution: Data provided by OpenWeatherMap
friendly_name: OpenWeatherMap_daily
```
Thanks for your effort on this nice card!

**Comment by erkr** [comment]
@VDRainer 
Well spotted. Didn't notice that before. Same issue for me:
![image](https://user-images.githubusercontent.com/4363599/180821223-76062d09-1027-49a5-81f9-8ea6fb42b815.jpeg)

**Comment by aarondrabeck** [comment]
Should be resolved by #45

**Comment by VDRainer** [comment]
Yepp! Icons and values are in order. :+1:

**Comment by enriquerollon** [comment]
Something similar also happens with spanish AEMET OpenData integration, values of daily forecast are one day off:

<img width="499" alt="Captura de Pantalla 2022-08-13 a las 18 01 50" src="https://user-images.githubusercontent.com/85040979/184502160-96ae1382-fa5d-4f50-bf62-b14f2ff6f6ba.png">

<img width="374" alt="Captura de Pantalla 2022-08-13 a las 18 22 20" src="https://user-images.githubusercontent.com/85040979/184502503-f65c42ac-c05c-4426-a9b1-5800e800cbcd.png">

This is the entity that provides the data: 

```
temperature: 26.7
temperature_unit: °C
humidity: 41
pressure: 1013.7
pressure_unit: hPa
wind_bearing: 180
wind_speed: 20
wind_speed_unit: km/h
visibility_unit: km
precipitation_unit: mm
forecast: 
- condition: sunny
  precipitation_probability: null
  datetime: '2022-08-13T22:00:00+00:00'
  wind_bearing: 225
  temperature: 31
  templow: 17
  wind_speed: 20
- condition: sunny
  precipitation_probability: null
  datetime: '2022-08-14T22:00:00+00:00'
  wind_bearing: 225
  temperature: 31
  templow: 16
  wind_speed: 10
- condition: sunny
  precipitation_probability: 5
  datetime: '2022-08-15T22:00:00+00:00'
  wind_bearing: 225
  temperature: 29
  templow: 18
  wind_speed: 20
- condition: partlycloudy
  precipitation_probability: 15
  datetime: '2022-08-16T22:00:00+00:00'
  wind_bearing: 270
  temperature: 28
  templow: 16
  wind_speed: 5
- condition: partlycloudy
  precipitation_probability: null
  datetime: '2022-08-17T22:00:00+00:00'
  wind_bearing: 0
  temperature: 29
  templow: 16
  wind_speed: 10
- condition: sunny
  precipitation_probability: null
  datetime: '2022-08-18T22:00:00+00:00'
  wind_bearing: null
  temperature: 31
  templow: 16

attribution: Powered by AEMET OpenData
friendly_name: AEMET daily
```

Thank you for your great work!
