### ISSUE TITLE
Error In Loading Data

### ISSUE THREAD

**Issue by spencerthayer** [Makin-Things/platinum-weather-card#34]
**Checklist:**

- [x] I updated to the latest version available
- [x] I cleared the cache of my browser

**Release with the issue:**

0.0.3

**Browser and Operating System:**

- Home Assistant 2022.7.5
- Chrome & Firefox

**Description of problem:**

The weather data isn't loading as shown below.
![Screen Shot 2022-07-19 at 1 51 27 PM](https://user-images.githubusercontent.com/1019815/179846326-1f12d1a8-edef-4d1e-ac8c-3fccb02facdf.png)

**Javascript errors shown in the web inspector (if applicable):**

```console
Uncaught (in promise) TypeError: can't access property "forEach", this._config.section_order is undefined
    render http://192.168.0.20:8123/hacsfiles/platinum-weather-card/platinum-weather-card-ec361ffe.js:195
    update http://192.168.0.20:8123/hacsfiles/platinum-weather-card/platinum-weather-card-ec361ffe.js:37
    performUpdate http://192.168.0.20:8123/hacsfiles/platinum-weather-card/platinum-weather-card-ec361ffe.js:25
    scheduleUpdate http://192.168.0.20:8123/hacsfiles/platinum-weather-card/platinum-weather-card-ec361ffe.js:25
    _$EC http://192.168.0.20:8123/hacsfiles/platinum-weather-card/platinum-weather-card-ec361ffe.js:25
platinum-weather-card-ec361ffe.js:195:376
```

**Comment by DavidFW1960** [comment]
Did you add the weather entity to the card configuration? Can you show your code (yaml) for the card

**Comment by spencerthayer** [comment]
```yaml
card_config_version: 4
section_order:
  - title
  - overview
  - extended
  - slots
  - daily_forecast
show_section_title: false
type: custom:platinum-weather-card
```

I don't see where in the YAML to connect it to `weather.home`.
