### ISSUE TITLE
Fatal error causes view to crash

### ISSUE THREAD

**Issue by justinhelmer** [Makin-Things/platinum-weather-card#37]
First, thanks for this truly promising card. I was previously using the `custom-weather-card` and stopped using it due to its limitations. Just using the GUI to set up the card, I can see the potential.

**Checklist:**

- [X] I updated to the latest version available
- [X] I cleared the cache of my browser

**Release with the issue:**

0.0.3

**Last working release (if known):**

Unknown

**Browser and Operating System:**

Chrome 103.0.5060.114
Windows 10

**Description of problem:**

The problem is, when I create the card and then save it, some runtime JS causes the entire view to crash - preventing any card from rendering. When I remove the card using the manual JSON editor, all is well.

![plat3](https://user-images.githubusercontent.com/1403438/180611645-c224357e-d807-4efa-b188-da979ce2b71d.PNG)

**Javascript errors shown in the web inspector (if applicable):**

![plat1](https://user-images.githubusercontent.com/1403438/180611641-600a6a2f-b7e2-4f00-86d9-5dc7298bc551.png)
![plat2](https://user-images.githubusercontent.com/1403438/180611643-baae9310-4c9e-45e0-acdd-68b99788f098.png)

**Additional information:**

Interestingly, the card renders just fine, as expected, when creating it through the GUI - it is only after saving it that the problem occurs.

Here is the card configuration:

```
      - card_config_version: 4
        entity_apparent_temp: sensor.openweathermap_feels_like_temperature
        entity_current_conditions: sensor.openweathermap_condition
        entity_current_text: sensor.openweathermap_condition
        entity_forecast_icon_1: weather.openweathermap
        entity_forecast_max: weather.thermostat
        entity_forecast_min: weather.thermostat
        entity_humidity: sensor.openweathermap_humidity
        entity_pop: sensor.openweathermap_rain
        entity_possible_today: sensor.openweathermap_rain
        entity_sun: sun.sun
        entity_temperature: weather.openweathermap
        entity_uv_alert_summary: sensor.openweathermap_uv_index
        entity_wind_bearing: sensor.openweathermap_wind_bearing
        entity_wind_speed: sensor.openweathermap_wind_speed
        extended_use_attr: false
        section_order:
          - title
          - overview
          - extended
          - slots
          - daily_forecast
        show_decimals: false
        show_section_daily_forecast: false
        show_section_extended: false
        show_section_overview: true
        show_section_slots: true
        show_section_title: true
        show_separator: false
        slot_l1: forecast_max
        slot_l2: forecast_min
        slot_l3: wind
        slot_l4: sun_next
        slot_l5: remove
        slot_l6: remove
        slot_l7: remove
        slot_l8: remove
        slot_r1: popforecast
        slot_r2: humidity
        slot_r3: uv_summary
        slot_r4: sun_following
        slot_r5: remove
        slot_r6: remove
        slot_r7: remove
        slot_r8: remove
        text_card_title: Weather in San Mateo, CA
        type: custom:platinum-weather-card
```
Thanks!
