### ISSUE TITLE
OpenWeatherMap not supported?

### ISSUE THREAD

**Issue by itsCARLsanity** [Makin-Things/platinum-weather-card#66]
**Checklist:**

- [Yes] I updated to the latest version available - release 1.02
- [Yes] I cleared the cache of my browser

Home Assistant 2022.11.1
Operating System 9.0

**Release with the issue:** 1.02

**Last working release (if known):** N/A

**Browser and Operating System:** Google Chrome 107.0.5304.88 / Windows 10

**Description of problem:**

OpenWeatherMap is not supported. Its sensors are not being read correctly by the Daily Forecast section. See pics for details.

![image](https://user-images.githubusercontent.com/17161608/200122120-d8badb46-4f48-4a1b-a856-c848cbd114e7.png)

Here are the values/attribute values of my OpenWeatherMap integration

![image](https://user-images.githubusercontent.com/17161608/200122205-f3baf036-131a-4eef-a21c-0c0d5e11621e.png)

Adding full attributes here
```
temperature: 26.7
temperature_unit: °C
humidity: 83
pressure: 1013
pressure_unit: hPa
wind_bearing: 80
wind_speed: 5.54
wind_speed_unit: km/h
visibility_unit: km
precipitation_unit: mm
forecast: 
- condition: partlycloudy
  precipitation_probability: 45
  datetime: '2022-11-05T15:00:00+00:00'
  wind_bearing: 78
  temperature: 26.4
  pressure: 1013
  wind_speed: 8.32
  precipitation: 0
- condition: partlycloudy
  precipitation_probability: 45
  datetime: '2022-11-05T18:00:00+00:00'
  wind_bearing: 60
  temperature: 25.6
  pressure: 1012
  wind_speed: 6.95
  precipitation: 0
- condition: partlycloudy
  precipitation_probability: 26
  datetime: '2022-11-05T21:00:00+00:00'
  wind_bearing: 54
  temperature: 24.9
  pressure: 1012
  wind_speed: 5.94
  precipitation: 0
- condition: partlycloudy
  precipitation_probability: 26
  datetime: '2022-11-06T00:00:00+00:00'
  wind_bearing: 81
  temperature: 26.5
  pressure: 1014
  wind_speed: 4.43
  precipitation: 0
- condition: partlycloudy
  precipitation_probability: 26
  datetime: '2022-11-06T03:00:00+00:00'
  wind_bearing: 102
  temperature: 30.1
  pressure: 1013
  wind_speed: 5.18
  precipitation: 0
- condition: rainy
  precipitation_probability: 50
  datetime: '2022-11-06T06:00:00+00:00'
  wind_bearing: 79
  temperature: 30.6
  pressure: 1010
  wind_speed: 14.29
  precipitation: 1.02
- condition: rainy
  precipitation_probability: 36
  datetime: '2022-11-06T09:00:00+00:00'
  wind_bearing: 91
  temperature: 28.1
  pressure: 1010
  wind_speed: 13.39
  precipitation: 0.3
- condition: cloudy
  precipitation_probability: 28
  datetime: '2022-11-06T12:00:00+00:00'
  wind_bearing: 83
  temperature: 26.3
  pressure: 1012
  wind_speed: 8.75
  precipitation: 0
- condition: cloudy
  precipitation_probability: 26
  datetime: '2022-11-06T15:00:00+00:00'
  wind_bearing: 70
  temperature: 25.6
  pressure: 1012
  wind_speed: 8.03
  precipitation: 0
- condition: cloudy
  precipitation_probability: 22
  datetime: '2022-11-06T18:00:00+00:00'
  wind_bearing: 53
  temperature: 25.2
  pressure: 1011
  wind_speed: 7.31
  precipitation: 0
- condition: cloudy
  precipitation_probability: 18
  datetime: '2022-11-06T21:00:00+00:00'
  wind_bearing: 60
  temperature: 25.1
  pressure: 1011
  wind_speed: 5.69
  precipitation: 0
- condition: cloudy
  precipitation_probability: 22
  datetime: '2022-11-07T00:00:00+00:00'
  wind_bearing: 86
  temperature: 26.8
  pressure: 1012
  wind_speed: 4.1
  precipitation: 0
- condition: rainy
  precipitation_probability: 42
  datetime: '2022-11-07T03:00:00+00:00'
  wind_bearing: 97
  temperature: 29.8
  pressure: 1012
  wind_speed: 5.69
  precipitation: 0.12
- condition: rainy
  precipitation_probability: 55
  datetime: '2022-11-07T06:00:00+00:00'
  wind_bearing: 61
  temperature: 30
  pressure: 1009
  wind_speed: 8.1
  precipitation: 1.39
- condition: rainy
  precipitation_probability: 36
  datetime: '2022-11-07T09:00:00+00:00'
  wind_bearing: 82
  temperature: 28.5
  pressure: 1009
  wind_speed: 11.09
  precipitation: 0.13
- condition: cloudy
  precipitation_probability: 28
  datetime: '2022-11-07T12:00:00+00:00'
  wind_bearing: 89
  temperature: 26.5
  pressure: 1011
  wind_speed: 11.3
  precipitation: 0
- condition: cloudy
  precipitation_probability: 14
  datetime: '2022-11-07T15:00:00+00:00'
  wind_bearing: 88
  temperature: 25.8
  pressure: 1011
  wind_speed: 10.01
  precipitation: 0
- condition: cloudy
  precipitation_probability: 7
  datetime: '2022-11-07T18:00:00+00:00'
  wind_bearing: 85
  temperature: 25.6
  pressure: 1010
  wind_speed: 7.38
  precipitation: 0
- condition: cloudy
  precipitation_probability: 13
  datetime: '2022-11-07T21:00:00+00:00'
  wind_bearing: 70
  temperature: 25.6
  pressure: 1010
  wind_speed: 6.05
  precipitation: 0
- condition: cloudy
  precipitation_probability: 13
  datetime: '2022-11-08T00:00:00+00:00'
  wind_bearing: 72
  temperature: 26.8
  pressure: 1012
  wind_speed: 4.1
  precipitation: 0
- condition: partlycloudy
  precipitation_probability: 17
  datetime: '2022-11-08T03:00:00+00:00'
  wind_bearing: 114
  temperature: 29.8
  pressure: 1011
  wind_speed: 3.46
  precipitation: 0
- condition: rainy
  precipitation_probability: 25
  datetime: '2022-11-08T06:00:00+00:00'
  wind_bearing: 95
  temperature: 30.6
  pressure: 1008
  wind_speed: 3.96
  precipitation: 0.11
- condition: rainy
  precipitation_probability: 58
  datetime: '2022-11-08T09:00:00+00:00'
  wind_bearing: 99
  temperature: 28.8
  pressure: 1009
  wind_speed: 7.52
  precipitation: 1.67
- condition: rainy
  precipitation_probability: 66
  datetime: '2022-11-08T12:00:00+00:00'
  wind_bearing: 88
  temperature: 26.4
  pressure: 1010
  wind_speed: 10.94
  precipitation: 0.56
- condition: rainy
  precipitation_probability: 42
  datetime: '2022-11-08T15:00:00+00:00'
  wind_bearing: 88
  temperature: 25.7
  pressure: 1011
  wind_speed: 8.71
  precipitation: 0.3
- condition: partlycloudy
  precipitation_probability: 34
  datetime: '2022-11-08T18:00:00+00:00'
  wind_bearing: 83
  temperature: 25.4
  pressure: 1009
  wind_speed: 6.91
  precipitation: 0
- condition: cloudy
  precipitation_probability: 7
  datetime: '2022-11-08T21:00:00+00:00'
  wind_bearing: 50
  temperature: 25.3
  pressure: 1009
  wind_speed: 5.4
  precipitation: 0
- condition: cloudy
  precipitation_probability: 7
  datetime: '2022-11-09T00:00:00+00:00'
  wind_bearing: 99
  temperature: 26.6
  pressure: 1011
  wind_speed: 4
  precipitation: 0
- condition: cloudy
  precipitation_probability: 7
  datetime: '2022-11-09T03:00:00+00:00'
  wind_bearing: 157
  temperature: 29.8
  pressure: 1010
  wind_speed: 4.75
  precipitation: 0
- condition: rainy
  precipitation_probability: 45
  datetime: '2022-11-09T06:00:00+00:00'
  wind_bearing: 119
  temperature: 30.8
  pressure: 1008
  wind_speed: 11.02
  precipitation: 0.15
- condition: rainy
  precipitation_probability: 63
  datetime: '2022-11-09T09:00:00+00:00'
  wind_bearing: 96
  temperature: 29.1
  pressure: 1009
  wind_speed: 9.18
  precipitation: 0.17
- condition: rainy
  precipitation_probability: 76
  datetime: '2022-11-09T12:00:00+00:00'
  wind_bearing: 83
  temperature: 26.6
  pressure: 1011
  wind_speed: 9.76
  precipitation: 0.5
- condition: rainy
  precipitation_probability: 29
  datetime: '2022-11-09T15:00:00+00:00'
  wind_bearing: 90
  temperature: 26.1
  pressure: 1011
  wind_speed: 8.17
  precipitation: 0.22
- condition: cloudy
  precipitation_probability: 24
  datetime: '2022-11-09T18:00:00+00:00'
  wind_bearing: 81
  temperature: 25.8
  pressure: 1010
  wind_speed: 7.31
  precipitation: 0
- condition: cloudy
  precipitation_probability: 16
  datetime: '2022-11-09T21:00:00+00:00'
  wind_bearing: 67
  temperature: 25.5
  pressure: 1010
  wind_speed: 6.7
  precipitation: 0
- condition: cloudy
  precipitation_probability: 16
  datetime: '2022-11-10T00:00:00+00:00'
  wind_bearing: 84
  temperature: 26.9
  pressure: 1011
  wind_speed: 5.22
  precipitation: 0
- condition: cloudy
  precipitation_probability: 6
  datetime: '2022-11-10T03:00:00+00:00'
  wind_bearing: 136
  temperature: 29.9
  pressure: 1011
  wind_speed: 5.36
  precipitation: 0
- condition: rainy
  precipitation_probability: 44
  datetime: '2022-11-10T06:00:00+00:00'
  wind_bearing: 105
  temperature: 30.8
  pressure: 1009
  wind_speed: 9.36
  precipitation: 0.29
- condition: rainy
  precipitation_probability: 51
  datetime: '2022-11-10T09:00:00+00:00'
  wind_bearing: 111
  temperature: 28.7
  pressure: 1009
  wind_speed: 7.52
  precipitation: 0.15
- condition: cloudy
  precipitation_probability: 41
  datetime: '2022-11-10T12:00:00+00:00'
  wind_bearing: 93
  temperature: 26.9
  pressure: 1011
  wind_speed: 9.61
  precipitation: 0

attribution: Data provided by OpenWeatherMap
friendly_name: OpenWeatherMap
```

All fields are available though, I'm not 100% sure why the card doesn't see this. 

![image](https://user-images.githubusercontent.com/17161608/200122265-8b59ad21-f466-45ab-aacb-a9698558e4c0.png)
