### ISSUE TITLE
Met Office - value needs to have a number

### ISSUE THREAD

**Issue by DustyArmstrong** [Makin-Things/platinum-weather-card#90]
**Checklist:**

- [x] I updated to the latest version available
- [x] I cleared the cache of my browser

**Release with the issue:**
1.0.5
**Last working release (if known):**
N/A
**Browser and Operating System:**
Windows 10, Firefox 113.0.2

Occurs on all OS, configuration issue with card.

**Description of problem:**
When trying to configure the weather forecast max/min temperatures, error below is returned. 

`'entity_forecast_min_1=sensor.met_office_REDACTED_temperature_daily' value needs to have a number`

Numerical value is provided by Met Office API, should be displayed as normal. Have tested this with other elements which do display the number correctly, this only appears to be an issue with the min/max on the forecast section. 

I have tried to use other readings such as `Met Office Daily` but this returns a different error `'entity_forecast_min_1 attribute forecast[1].templow not found`, though this one does arguably make sense if that specific reading is not sent by the API in that way.

It would be good if I can either disable the temperatures entirely (when the API doesn't provide the specific information it's looking for) or if there is a possible fix for this.

**Comment by DustyArmstrong** [comment]
Thought I would try creating a dummy sensor with a numerical value to see what it was looking for, still returns the same error. I assume I am just missing something, I tried casting it to a string and declaring it as an integer too but still the same, not sure what data it's expecting.

**Comment by DustyArmstrong** [comment]
OK so it seems to be down to the fact that the Met Office readings do not include `templow`, so it's unable to display it correctly. Having the option to display just the temperature instead of high/low would be ideal, but in the meantime I will try to figure out a way to inject `templow` with an arbitrary reading from the normal `temperature` reading.  

I suppose this is a feature request then rather than a bug, sorry!

**Comment by DavidFW1960** [comment]
as a suggestion, use something like statistics integration (or the custom average component) to generate the high/low and point the entity in the card to that. Of course this is not a bug with the card but a deficiency in the weather integration you are using. The card can point to ANY entity you want it to BTW.

**Comment by DustyArmstrong** [comment]
> as a suggestion, use something like statistics integration (or the custom average component) to generate the high/low and point the entity in the card to that. Of course this is not a bug with the card but a deficiency in the weather integration you are using. The card can point to ANY entity you want it to BTW.

Thanks, I am trying to work out (with my limited skills) how I can just pass the temperature readings I _do_ have through a separate entity. It's expecting an index with `templow` and `temperature` rather than just anything, otherwise it still fails with a different error `entity_forecast_min_1 attribute forecast[1].templow not found`.

**Comment by DavidFW1960** [comment]
Can you post a screenshot of the states for the weather entities here please. Is it a weather integration you are using or individual sensors? Also post the yaml code for the card config.

**Comment by DustyArmstrong** [comment]
Thanks for getting back to me. I am using the Met Office integration, from the UK. I hope you don't mind, I have redacted my location for privacy. I use the Met Office one as it seems to be the most accurate.

As you can see below, the states summary only includes `temperature`, not `templow` _and_ `temperature`. I have tested, and if I inject a `templow: 0` to the state then I can add it to the card successfully. I'm not knowledgeable enough to know how to do this through the configuration, I'd be happy with that or just a new entity that I can create with the right `temperature` and `templow` readings created from this existing state. 

I can of course access the reading(s) with: 

`{{ state_attr('weather.met_office_REDACTED_daily', 'forecast')[0]['temperature'] }}`

I just don't know how to translate that into a new entity or inject `templow` to the existing state.

**STATES**

```
temperature: 16
temperature_unit: °C
humidity: 76
pressure_unit: hPa
wind_bearing: NE
wind_speed: 28.97
wind_speed_unit: km/h
visibility_unit: km
precipitation_unit: mm
forecast:
  - datetime: '2023-06-07T12:00:00+00:00'
    condition: sunny
    precipitation_probability: 4
    wind_bearing: ENE
    temperature: 18
    wind_speed: 28.97
  - datetime: '2023-06-08T12:00:00+00:00'
    condition: cloudy
    precipitation_probability: 4
    wind_bearing: ENE
    temperature: 17
    wind_speed: 28.97
  - datetime: '2023-06-09T12:00:00+00:00'
    condition: cloudy
    precipitation_probability: 12
    wind_bearing: ENE
    temperature: 18
    wind_speed: 25.75
  - datetime: '2023-06-10T12:00:00+00:00'
    condition: cloudy
    precipitation_probability: 34
    wind_bearing: NNE
    temperature: 19
    wind_speed: 14.48
attribution: Data provided by the Met Office
friendly_name: Met Office REDACTED Daily
```

**CARD YAML**
```
card_config_version: 8
custom1_icon: mdi:radar
custom1_value: sensor.met_office_REDACTED_weather_3_hourly
daily_forecast_days: 4
entity_apparent_temp: sensor.met_office_REDACTED_feels_like_temperature_3_hourly
entity_forecast_icon: weather.met_office_REDACTED_3_hourly
entity_forecast_icon_1: weather.met_office_REDACTED_daily
entity_forecast_max: weather.met_office_REDACTED_daily
entity_humidity: weather.met_office_REDACTED_3_hourly
entity_pop: sensor.met_office_REDACTED_probability_of_precipitation_3_hourly
entity_pop_1: weather.met_office_REDACTED_daily
entity_pos: sensor.met_office_REDACTED_probability_of_precipitation_3_hourly
entity_pressure: weather.met_office_REDACTED_daily
entity_summary_1: weather.met_office_REDACTED_daily
entity_sun: sun.sun
entity_temperature: sensor.met_office_REDACTED_temperature_3_hourly
entity_uv_alert_summary: sensor.met_office_REDACTED_uv_index_3_hourly
entity_wind_bearing: weather.met_office_REDACTED_3_hourly
entity_wind_speed: sensor.met_office_REDACTED_wind_speed_3_hourly
option_locale: GB
section_order:
  - overview
  - extended
  - slots
  - daily_forecast
show_section_daily_forecast: true
slot_l1: forecast_max
slot_l2: custom1
slot_l3: wind
slot_l4: remove
slot_l5: sun_next
slot_l6: remove
slot_l7: remove
slot_l8: remove
slot_r1: popforecast
slot_r2: humidity
slot_r3: uv_summary
slot_r4: remove
slot_r5: sun_following
slot_r6: remove
slot_r7: remove
slot_r8: remove
type: custom:platinum-weather-card
```

**Comment by DustyArmstrong** [comment]
I have done some testing, and was able to get the following attributes by using the below: 

```
        tempfix:
            friendly_name: "tempfix"
            value_template: "sunny"
            attribute_templates:
                forecast: "{{ state_attr('weather.met_office_REDACTED_daily', 'forecast')[0]['temperature'], state_attr('weather.met_office_REDACTED_daily', 'forecast')[1]['temperature'], state_attr('weather.met_office_REDACTED_daily', 'forecast')[2]['temperature'], state_attr('weather.met_office_REDACTED_daily', 'forecast')[3]['temperature'] }}"
```

```
forecast:
  - 18
  - 17
  - 18
  - 19
friendly_name: tempfix
```

But even if I add in `templow` like my original API call, I still get the `value needs to have a number` error. I don't get this error however if I add in `templow` to the API output. What data is it expecting? I can't see any difference between them?

```
forecast:
  - templow: 18
  - templow: 17
  - templow: 18
  - templow: 19
friendly_name: tempfix
```

```
forecast:
  - datetime: '2023-06-07T12:00:00+00:00'
    condition: sunny
    precipitation_probability: 4
    wind_bearing: ENE
    temperature: 18
    templow: 18
    wind_speed: 28.97
  - datetime: '2023-06-08T12:00:00+00:00'
    condition: cloudy
    precipitation_probability: 4
    wind_bearing: ENE
    temperature: 17
    templow: 17
    wind_speed: 28.97
  - datetime: '2023-06-09T12:00:00+00:00'
    condition: cloudy
    precipitation_probability: 12
    wind_bearing: ENE
    temperature: 18
    templow: 18
    wind_speed: 25.75
```
